const sampleHosts = [
  {
    name: "Priya Bhatt",
    username: "priya_relocates",
    email: "priya@example.com",
    dob: "1998-04-12",
    institution: "Google",
    isVerifiedHost: true,
  },
  {
    name: "Arjun Kannan",
    username: "arjun_stays",
    email: "arjun@example.com",
    dob: "1999-11-03",
    institution: "IIT Bombay",
    isVerifiedHost: false,
  },
  {
    name: "Meera Shah",
    username: "meera_shah",
    email: "meera@example.com",
    dob: "1997-08-16",
    institution: "University of Mumbai",
    isVerifiedHost: true,
  },
  {
    name: "Rohan Iyer",
    username: "rohan_iyer",
    email: "rohan@example.com",
    dob: "1998-06-21",
    institution: "BITS Pilani",
    isVerifiedHost: false,
  },
  {
    name: "Sana Khan",
    username: "sana_khan",
    email: "sana@example.com",
    dob: "2000-01-09",
    institution: "NIT Trichy",
    isVerifiedHost: true,
  },
  {
    name: "Vikram Nair",
    username: "vikram_nair",
    email: "vikram@example.com",
    dob: "1996-12-05",
    institution: "Anna University",
    isVerifiedHost: true,
  },
  {
    name: "Ananya Rao",
    username: "ananya_rao",
    email: "ananya@example.com",
    dob: "1999-03-14",
    institution: "IISc Bengaluru",
    isVerifiedHost: true,
  },
  {
    name: "Kabir Mehta",
    username: "kabir_mehta",
    email: "kabir@example.com",
    dob: "1998-09-27",
    institution: "Symbiosis Pune",
    isVerifiedHost: false,
  },
  {
    name: "Nisha Menon",
    username: "nisha_menon",
    email: "nisha@example.com",
    dob: "1997-05-18",
    institution: "TCS Bengaluru",
    isVerifiedHost: true,
  },
  {
    name: "Dev Patel",
    username: "dev_patel",
    email: "dev@example.com",
    dob: "2000-02-22",
    institution: "IIT Madras",
    isVerifiedHost: true,
  },
];

const sampleListings = [
  {
    title: "Sunny Private Room",
    description:
      "A furnished private room in a quiet shared home, with a desk for coursework and a short commute to campus. Best suited to a student relocating for a semester.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    },
    price: 18000,
    nearestCampus: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Furnished Studio",
    description:
      "A move-in-ready studio close to Koramangala offices and cafes, with reliable Wi-Fi and a kitchen for a 3 to 6 month internship stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 26000,
    nearestCampus: "Bengaluru Tech Hub",
    location: "Koramangala, Bengaluru",
    country: "India",
    hostIndex: 0,
    verificationStatus: "pending",
  },
  {
    title: "Shared Apartment",
    description:
      "A bright room in a three-bedroom apartment with a shared kitchen and study area. A practical base for a semester in Mumbai.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    },
    price: 22000,
    nearestCampus: "University of Mumbai",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 1,
    verificationStatus: "unverified",
  },
  {
    title: "Quiet Room",
    description:
      "A private, furnished room with a work desk and metro access for interns working in HITEC City. Available for medium-term stays.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=800&q=80",
    },
    price: 17000,
    nearestCampus: "HITEC City",
    location: "Madhapur, Hyderabad",
    country: "India",
    hostIndex: 1,
    verificationStatus: "flagged",
  },
  {
    title: "Compact Room",
    description:
      "A simple furnished room with fast Wi-Fi, laundry access, and a direct bus route to campus. Designed for a one-semester move.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=800&q=80",
    },
    price: 14500,
    nearestCampus: "Pune University",
    location: "Aundh, Pune",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Intern Room",
    description:
      "A furnished room in a shared apartment near Bengaluru's office parks, with a housemate-friendly layout and flexible 1 to 6 month availability.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
    },
    price: 16000,
    nearestCampus: "Whitefield Tech Park",
    location: "Whitefield, Bengaluru",
    country: "India",
    hostIndex: 1,
    verificationStatus: "unverified",
  },
  {
    title: "Bright Studio",
    description:
      "A fully furnished studio with a study desk, pantry, and quick access to the metro for students spending a semester in Delhi.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    },
    price: 19500,
    nearestCampus: "JNU",
    location: "Malviya Nagar, New Delhi",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Comfort Room",
    description:
      "A bright room in a shared apartment with dedicated storage, quiet hours, and a quick commute to the university district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 21000,
    nearestCampus: "IIT Bombay",
    location: "Andheri East, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "pending",
  },
  {
    title: "Work-Friendly Room",
    description:
      "A modern room with a study desk, strong Wi-Fi, and a flexible lease for interns moving into Bengaluru for a few months.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
    },
    price: 23000,
    nearestCampus: "Whitefield Tech Park",
    location: "Whitefield, Bengaluru",
    country: "India",
    hostIndex: 3,
    verificationStatus: "verified",
  },
  {
    title: "Minimal Private Room",
    description:
      "A crisp, furnished room with a clean setup, balcony access, and a practical base for a student semester in Pune.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 15500,
    nearestCampus: "Pune University",
    location: "Baner, Pune",
    country: "India",
    hostIndex: 4,
    verificationStatus: "verified",
  },
  {
    title: "City View Room",
    description:
      "A light-filled room in a curated shared home with a work desk and easy connectivity to Hyderabad's tech corridor.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
    },
    price: 18000,
    nearestCampus: "HITEC City",
    location: "Gachibowli, Hyderabad",
    country: "India",
    hostIndex: 5,
    verificationStatus: "pending",
  },
  {
    title: "Modern One-Bedroom",
    description:
      "A move-in-ready room with a kitchen corner, good daylight, and a calm environment for a medium-term placement.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    },
    price: 28000,
    nearestCampus: "BITS Pilani",
    location: "Pilani, Rajasthan",
    country: "India",
    hostIndex: 3,
    verificationStatus: "verified",
  },
  {
    title: "Quiet Corner Room",
    description:
      "A comfortable room in a peaceful shared home with fast internet and a manageable commute to campus life.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 17000,
    nearestCampus: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    country: "India",
    hostIndex: 4,
    verificationStatus: "unverified",
  },
  {
    title: "Studio Near Campus",
    description:
      "A compact, comfortable studio with a bed nook, desk space, and a cozy setup for 1 to 6 month stays near college.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=800&q=80",
    },
    price: 24000,
    nearestCampus: "Anna University",
    location: "Guindy, Chennai",
    country: "India",
    hostIndex: 5,
    verificationStatus: "verified",
  },
  {
    title: "Eco Room",
    description:
      "A clean, budget-friendly room with shared amenities and a good location for students relocating for a semester.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
    },
    price: 16500,
    nearestCampus: "University of Mumbai",
    location: "Kurla, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Shared Green Room",
    description:
      "A lively shared room with good natural light, storage, and flexible lease terms for relocating interns and students.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 14500,
    nearestCampus: "IIT Delhi",
    location: "Khanpur, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "unverified",
  },
  {
    title: "Premium Studio",
    description:
      "A polished room with a modern kitchen setup, brighter finish, and an easy route to the city's internship cluster.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    },
    price: 30000,
    nearestCampus: "IISc Bengaluru",
    location: "Indiranagar, Bengaluru",
    country: "India",
    hostIndex: 1,
    verificationStatus: "verified",
  },
  {
    title: "Garden Room",
    description: "A calm furnished room near Bengaluru's university and technology corridor, with a desk and shared garden access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    },
    price: 18500,
    nearestCampus: "IISc Bengaluru",
    location: "Malleshwaram, Bengaluru",
    country: "India",
    hostIndex: 6,
    verificationStatus: "verified",
  },
  {
    title: "Metro Side Room",
    description: "A practical private room close to offices, metro links, and several Bengaluru institutions for a flexible lease.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=800&q=80",
    },
    price: 20000,
    nearestCampus: "Bengaluru Tech Hub",
    location: "Indiranagar, Bengaluru",
    country: "India",
    hostIndex: 8,
    verificationStatus: "verified",
  },
  {
    title: "Powai Study Room",
    description: "A furnished room with a quiet study corner and quick access to Powai's university and workplace hubs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 20500,
    nearestCampus: "IIT Bombay",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Lakeside Shared Room",
    description: "A bright shared-home room near Powai Lake, with a desk, storage, and an easy commute to nearby institutions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
    },
    price: 17500,
    nearestCampus: "University of Mumbai",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 7,
    verificationStatus: "pending",
  },
  {
    title: "South Delhi Studio",
    description: "A compact studio with a dedicated work area and dependable transport links to South Delhi campuses.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    },
    price: 22500,
    nearestCampus: "JNU",
    location: "Vasant Kunj, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Hauz Khas Private Room",
    description: "A move-in-ready private room near cafes, transit, and the student neighborhoods around IIT Delhi and JNU.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    },
    price: 19000,
    nearestCampus: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    hostIndex: 6,
    verificationStatus: "pending",
  },
  {
    title: "Aundh Student Room",
    description: "A comfortable furnished room with Wi-Fi and a short commute to Pune's university and research districts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
    },
    price: 16000,
    nearestCampus: "Pune University",
    location: "Aundh, Pune",
    country: "India",
    hostIndex: 7,
    verificationStatus: "verified",
  },
  {
    title: "Tech Park Room",
    description: "A clean private room for interns, close to Bengaluru offices, cafes, and multiple daily commute routes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 21500,
    nearestCampus: "Whitefield Tech Park",
    location: "Brookefield, Bengaluru",
    country: "India",
    hostIndex: 8,
    verificationStatus: "verified",
  },
  {
    title: "Guindy Work Room",
    description: "A furnished room with a proper work desk and quick transport to Chennai's university and technology districts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=800&q=80",
    },
    price: 18500,
    nearestCampus: "Anna University",
    location: "Guindy, Chennai",
    country: "India",
    hostIndex: 9,
    verificationStatus: "verified",
  },
  {
    title: "Campus Edge Room",
    description: "A simple, well-connected room for a semester move, with shared amenities and a short route to campus.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
    },
    price: 15000,
    nearestCampus: "Symbiosis Pune",
    location: "Viman Nagar, Pune",
    country: "India",
    hostIndex: 7,
    verificationStatus: "unverified",
  },
];

module.exports = { data: sampleListings, hosts: sampleHosts };