const sampleHosts = [
  {
    name: "Priya Bhatt",
    username: "priya_relocates",
    email: "priya@example.com",
    dob: "1998-04-12",
    institution: "Google",
    isVerifiedHost: true,
  },
  {
    name: "Arjun Kannan",
    username: "arjun_stays",
    email: "arjun@example.com",
    dob: "1999-11-03",
    institution: "IIT Bombay",
    isVerifiedHost: false,
  },
  {
    name: "Meera Shah",
    username: "meera_shah",
    email: "meera@example.com",
    dob: "1997-08-16",
    institution: "University of Mumbai",
    isVerifiedHost: true,
  },
  {
    name: "Rohan Iyer",
    username: "rohan_iyer",
    email: "rohan@example.com",
    dob: "1998-06-21",
    institution: "BITS Pilani",
    isVerifiedHost: false,
  },
  {
    name: "Sana Khan",
    username: "sana_khan",
    email: "sana@example.com",
    dob: "2000-01-09",
    institution: "NIT Trichy",
    isVerifiedHost: true,
  },
  {
    name: "Vikram Nair",
    username: "vikram_nair",
    email: "vikram@example.com",
    dob: "1996-12-05",
    institution: "Anna University",
    isVerifiedHost: true,
  },
  {
    name: "Ananya Rao",
    username: "ananya_rao",
    email: "ananya@example.com",
    dob: "1999-03-14",
    institution: "IISc Bengaluru",
    isVerifiedHost: true,
  },
  {
    name: "Kabir Mehta",
    username: "kabir_mehta",
    email: "kabir@example.com",
    dob: "1998-09-27",
    institution: "Symbiosis Pune",
    isVerifiedHost: false,
  },
  {
    name: "Nisha Menon",
    username: "nisha_menon",
    email: "nisha@example.com",
    dob: "1997-05-18",
    institution: "TCS Bengaluru",
    isVerifiedHost: true,
  },
  {
    name: "Dev Patel",
    username: "dev_patel",
    email: "dev@example.com",
    dob: "2000-02-22",
    institution: "IIT Madras",
    isVerifiedHost: true,
  },
];

const sampleListings = [
  {
    title: "Sunlit Private Room",
    description:
      "A furnished private room in a quiet shared home, with a desk for coursework and a short commute to campus. Best suited to a student relocating for a semester.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    },
    price: 18000,
    nearestCampus: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Move-In Studio",
    description:
      "A move-in-ready studio close to Koramangala offices and cafes, with reliable Wi-Fi and a kitchen for a 3 to 6 month internship stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 26000,
    nearestCampus: "Bengaluru Tech Hub",
    location: "Koramangala, Bengaluru",
    country: "India",
    hostIndex: 0,
    verificationStatus: "pending",
  },
  {
    title: "Study Flatshare",
    description:
      "A bright room in a three-bedroom apartment with a shared kitchen and study area. A practical base for a semester in Mumbai.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    },
    price: 22000,
    nearestCampus: "University of Mumbai",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 1,
    verificationStatus: "unverified",
  },
  {
    title: "Quiet Workroom",
    description:
      "A private, furnished room with a work desk and metro access for interns working in HITEC City. Available for medium-term stays.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=800&q=80",
    },
    price: 17000,
    nearestCampus: "HITEC City",
    location: "Madhapur, Hyderabad",
    country: "India",
    hostIndex: 1,
    verificationStatus: "flagged",
  },
  {
    title: "Compact Campus Room",
    description:
      "A simple furnished room with fast Wi-Fi, laundry access, and a direct bus route to campus. Designed for a one-semester move.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=800&q=80",
    },
    price: 14500,
    nearestCampus: "Pune University",
    location: "Aundh, Pune",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Internship Room",
    description:
      "A furnished room in a shared apartment near Bengaluru's office parks, with a housemate-friendly layout and flexible 1 to 6 month availability.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
    },
    price: 16000,
    nearestCampus: "Whitefield Tech Park",
    location: "Whitefield, Bengaluru",
    country: "India",
    hostIndex: 1,
    verificationStatus: "unverified",
  },
  {
    title: "Bright Campus Studio",
    description:
      "A fully furnished studio with a study desk, pantry, and quick access to the metro for students spending a semester in Delhi.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    },
    price: 19500,
    nearestCampus: "JNU",
    location: "Malviya Nagar, New Delhi",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Comfortable Room",
    description:
      "A bright room in a shared apartment with dedicated storage, quiet hours, and a quick commute to the university district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    },
    price: 21000,
    nearestCampus: "IIT Bombay",
    location: "Andheri East, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "pending",
  },
  {
    title: "Work-Ready Room",
    description:
      "A modern room with a study desk, strong Wi-Fi, and a flexible lease for interns moving into Bengaluru for a few months.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
    },
    price: 23000,
    nearestCampus: "Whitefield Tech Park",
    location: "Whitefield, Bengaluru",
    country: "India",
    hostIndex: 3,
    verificationStatus: "verified",
  },
  {
    title: "Minimal Private Room",
    description:
      "A crisp, furnished room with a clean setup, balcony access, and a practical base for a student semester in Pune.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    },
    price: 15500,
    nearestCampus: "Pune University",
    location: "Baner, Pune",
    country: "India",
    hostIndex: 4,
    verificationStatus: "verified",
  },
  {
    title: "City-View Room",
    description:
      "A light-filled room in a curated shared home with a work desk and easy connectivity to Hyderabad's tech corridor.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
    },
    price: 18000,
    nearestCampus: "HITEC City",
    location: "Gachibowli, Hyderabad",
    country: "India",
    hostIndex: 5,
    verificationStatus: "pending",
  },
  {
    title: "Modern One-Bedroom",
    description:
      "A move-in-ready room with a kitchen corner, good daylight, and a calm environment for a medium-term placement.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    },
    price: 28000,
    nearestCampus: "BITS Pilani",
    location: "Pilani, Rajasthan",
    country: "India",
    hostIndex: 3,
    verificationStatus: "verified",
  },
  {
    title: "Quiet Corner Room",
    description:
      "A comfortable room in a peaceful shared home with fast internet and a manageable commute to campus life.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501045661006-fcebe0257c3f?auto=format&fit=crop&w=800&q=80",
    },
    price: 17000,
    nearestCampus: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    country: "India",
    hostIndex: 4,
    verificationStatus: "unverified",
  },
  {
    title: "Campus-Ready Studio",
    description:
      "A compact, comfortable studio with a bed nook, desk space, and a cozy setup for 1 to 6 month stays near college.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=800&q=80",
    },
    price: 24000,
    nearestCampus: "Anna University",
    location: "Guindy, Chennai",
    country: "India",
    hostIndex: 5,
    verificationStatus: "verified",
  },
  {
    title: "Eco Room",
    description:
      "A clean, budget-friendly room with shared amenities and a good location for students relocating for a semester.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    },
    price: 16500,
    nearestCampus: "University of Mumbai",
    location: "Kurla, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Green Shared Room",
    description:
      "A lively shared room with good natural light, storage, and flexible lease terms for relocating interns and students.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 14500,
    nearestCampus: "IIT Delhi",
    location: "Khanpur, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "unverified",
  },
  {
    title: "Premium Internship Studio",
    description:
      "A polished room with a modern kitchen setup, brighter finish, and an easy route to the city's internship cluster.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501045661006-fcebe0257c3f?auto=format&fit=crop&w=800&q=80",
    },
    price: 30000,
    nearestCampus: "IISc Bengaluru",
    location: "Indiranagar, Bengaluru",
    country: "India",
    hostIndex: 1,
    verificationStatus: "verified",
  },
  {
    title: "Garden Room",
    description:
      "A calm furnished room near Bengaluru's university and technology corridor, with a desk and shared garden access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=80",
    },
    price: 18500,
    nearestCampus: "IISc Bengaluru",
    location: "Malleshwaram, Bengaluru",
    country: "India",
    hostIndex: 6,
    verificationStatus: "verified",
  },
  {
    title: "Metro-Connected Room",
    description:
      "A practical private room close to offices, metro links, and several Bengaluru institutions for a flexible lease.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80",
    },
    price: 20000,
    nearestCampus: "Bengaluru Tech Hub",
    location: "Indiranagar, Bengaluru",
    country: "India",
    hostIndex: 8,
    verificationStatus: "verified",
  },
  {
    title: "Scholar's Room",
    description:
      "A furnished room with a quiet study corner and quick access to Powai's university and workplace hubs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
    },
    price: 20500,
    nearestCampus: "IIT Bombay",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 2,
    verificationStatus: "verified",
  },
  {
    title: "Lakeside Room",
    description:
      "A bright shared-home room near Powai Lake, with a desk, storage, and an easy commute to nearby institutions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    },
    price: 17500,
    nearestCampus: "University of Mumbai",
    location: "Powai, Mumbai",
    country: "India",
    hostIndex: 7,
    verificationStatus: "pending",
  },
  {
    title: "Work Studio",
    description:
      "A compact studio with a dedicated work area and dependable transport links to South Delhi campuses.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    },
    price: 22500,
    nearestCampus: "JNU",
    location: "Vasant Kunj, New Delhi",
    country: "India",
    hostIndex: 0,
    verificationStatus: "verified",
  },
  {
    title: "Private Room",
    description:
      "A move-in-ready private room near cafes, transit, and the student neighborhoods around IIT Delhi and JNU.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=80",
    },
    price: 19000,
    nearestCampus: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    hostIndex: 6,
    verificationStatus: "pending",
  },
  {
    title: "Semester Room",
    description:
      "A comfortable furnished room with Wi-Fi and a short commute to Pune's university and research districts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80",
    },
    price: 16000,
    nearestCampus: "Pune University",
    location: "Aundh, Pune",
    country: "India",
    hostIndex: 7,
    verificationStatus: "verified",
  },
  {
    title: "Tech-Ready Private Room",
    description:
      "A clean private room for interns, close to Bengaluru offices, cafes, and multiple daily commute routes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
    },
    price: 21500,
    nearestCampus: "Whitefield Tech Park",
    location: "Brookefield, Bengaluru",
    country: "India",
    hostIndex: 8,
    verificationStatus: "verified",
  },
  {
    title: "Work-Ready Room",
    description:
      "A furnished room with a proper work desk and quick transport to Chennai's university and technology districts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80",
    },
    price: 18500,
    nearestCampus: "Anna University",
    location: "Guindy, Chennai",
    country: "India",
    hostIndex: 9,
    verificationStatus: "verified",
  },
  {
    title: "Campus Edge Room",
    description:
      "A simple, well-connected room for a semester move, with shared amenities and a short route to campus.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=80",
    },
    price: 15000,
    nearestCampus: "Symbiosis Pune",
    location: "Viman Nagar, Pune",
    country: "India",
    hostIndex: 7,
    verificationStatus: "unverified",
  },
];

const sampleReviews = [
  {
    listingIndex: 0,
    authorIndex: 1,
    rating: 5,
    comment: "Quiet street and an easy commute to campus. The room was clean, bright, and ready for a semester move.",
  },
  {
    listingIndex: 0,
    authorIndex: 2,
    rating: 4,
    comment: "The host was responsive and the shared home felt comfortable. The desk was especially useful for coursework.",
  },
  {
    listingIndex: 1,
    authorIndex: 3,
    rating: 5,
    comment: "A practical studio for an internship, with reliable Wi-Fi and a short commute to the office park.",
  },
  {
    listingIndex: 2,
    authorIndex: 4,
    rating: 4,
    comment: "Good location and a welcoming shared apartment. The kitchen and study area worked well for a longer stay.",
  },
  {
    listingIndex: 3,
    authorIndex: 5,
    rating: 4,
    comment: "Quiet room with a useful desk and easy metro access. A comfortable base for my Hyderabad internship.",
  },
  {
    listingIndex: 4,
    authorIndex: 6,
    rating: 5,
    comment: "Simple, clean, and well connected to campus. The Wi-Fi and laundry access made the semester very easy.",
  },
  {
    listingIndex: 5,
    authorIndex: 7,
    rating: 4,
    comment: "Friendly housemates and a practical layout. The room had everything I needed for a short internship lease.",
  },
  {
    listingIndex: 6,
    authorIndex: 8,
    rating: 5,
    comment: "Bright studio with a proper study desk and a quick route to campus. It felt ready from day one.",
  },
  {
    listingIndex: 7,
    authorIndex: 9,
    rating: 4,
    comment: "Comfortable shared apartment with plenty of storage and a calm atmosphere. The commute was manageable.",
  },
  {
    listingIndex: 8,
    authorIndex: 0,
    rating: 5,
    comment: "Excellent setup for remote work and a very responsive host. The internet was reliable throughout my stay.",
  },
  {
    listingIndex: 9,
    authorIndex: 1,
    rating: 4,
    comment: "Clean private room in a convenient neighborhood. The balcony and natural light were a great bonus.",
  },
  {
    listingIndex: 10,
    authorIndex: 2,
    rating: 4,
    comment: "Good daylight and a peaceful shared home. Transport to the tech corridor was straightforward.",
  },
  {
    listingIndex: 11,
    authorIndex: 3,
    rating: 5,
    comment: "The kitchen corner was genuinely useful and the room was move-in ready. A great option near campus.",
  },
  {
    listingIndex: 12,
    authorIndex: 4,
    rating: 4,
    comment: "Peaceful place with fast internet and a reasonable commute. The room matched the listing description well.",
  },
  {
    listingIndex: 13,
    authorIndex: 5,
    rating: 5,
    comment: "Compact but thoughtfully arranged, with a comfortable bed nook and enough desk space for coursework.",
  },
  {
    listingIndex: 14,
    authorIndex: 6,
    rating: 4,
    comment: "Budget-friendly room in a useful location. Shared facilities were clean and easy to use.",
  },
  {
    listingIndex: 15,
    authorIndex: 7,
    rating: 4,
    comment: "Lively shared home with good light and enough storage. Flexible lease terms made relocating much easier.",
  },
  {
    listingIndex: 16,
    authorIndex: 8,
    rating: 5,
    comment: "Polished studio with a modern finish and a smooth commute to the internship district. Very comfortable overall.",
  },
  {
    listingIndex: 17,
    authorIndex: 9,
    rating: 5,
    comment: "Calm room with a lovely shared garden and a dedicated desk. The host made move-in simple.",
  },
  {
    listingIndex: 18,
    authorIndex: 0,
    rating: 4,
    comment: "Convenient location close to the metro and offices. The room was practical and well maintained.",
  },
  {
    listingIndex: 19,
    authorIndex: 1,
    rating: 5,
    comment: "Quiet study corner and a quick commute to IIT Bombay. The room worked especially well for exam season.",
  },
  {
    listingIndex: 20,
    authorIndex: 2,
    rating: 4,
    comment: "Bright room with good storage and a pleasant neighborhood. The shared spaces were kept tidy.",
  },
  {
    listingIndex: 21,
    authorIndex: 3,
    rating: 5,
    comment: "The studio was compact but well planned, with dependable transport to South Delhi campuses.",
  },
  {
    listingIndex: 22,
    authorIndex: 4,
    rating: 4,
    comment: "Great access to cafes and transit, and the room was ready for a semester move. Communication was clear.",
  },
  {
    listingIndex: 23,
    authorIndex: 5,
    rating: 5,
    comment: "Comfortable furnished room with strong Wi-Fi and an easy commute to the university district.",
  },
  {
    listingIndex: 24,
    authorIndex: 6,
    rating: 4,
    comment: "Clean private room close to offices and cafes. The daily commute was much easier than expected.",
  },
  {
    listingIndex: 25,
    authorIndex: 7,
    rating: 5,
    comment: "Proper work desk and reliable transport made this a strong choice for my Chennai placement.",
  },
  {
    listingIndex: 26,
    authorIndex: 8,
    rating: 4,
    comment: "Straightforward room with convenient shared amenities and a short route to campus.",
  },
  {
    listingIndex: 0,
    authorIndex: 9,
    rating: 5,
    comment: "The neighborhood was peaceful and the room had plenty of natural light. The host made the move-in process easy.",
  },
  {
    listingIndex: 1,
    authorIndex: 4,
    rating: 4,
    comment: "Well laid out studio with a useful kitchen and good access to cafes. It suited my three-month placement well.",
  },
  {
    listingIndex: 2,
    authorIndex: 6,
    rating: 5,
    comment: "The apartment was bright, social, and close to everything I needed. The study area was a real advantage.",
  },
  {
    listingIndex: 3,
    authorIndex: 8,
    rating: 4,
    comment: "A quiet place to work after office hours, with a straightforward commute and a helpful host.",
  },
  {
    listingIndex: 4,
    authorIndex: 0,
    rating: 4,
    comment: "The room is compact but thoughtfully arranged. I appreciated the direct bus route and clean shared spaces.",
  },
  {
    listingIndex: 5,
    authorIndex: 2,
    rating: 5,
    comment: "A very easy landing spot for an internship. The house was welcoming and the room had a comfortable work setup.",
  },
  {
    listingIndex: 6,
    authorIndex: 7,
    rating: 4,
    comment: "The studio gets great daylight and feels larger than expected. Metro access made campus days simple.",
  },
  {
    listingIndex: 7,
    authorIndex: 5,
    rating: 4,
    comment: "Good storage, quiet evenings, and a reliable commute. The listing was accurate and easy to settle into.",
  },
  {
    listingIndex: 8,
    authorIndex: 9,
    rating: 5,
    comment: "The desk and Wi-Fi were exactly what I needed for hybrid work. Everything felt considered and dependable.",
  },
  {
    listingIndex: 9,
    authorIndex: 3,
    rating: 4,
    comment: "A clean and calm room in a convenient part of Pune. The balcony made the space feel especially pleasant.",
  },
  {
    listingIndex: 10,
    authorIndex: 6,
    rating: 5,
    comment: "Bright room, easy transport, and a considerate shared-home setup. I would happily stay here again.",
  },
  {
    listingIndex: 11,
    authorIndex: 0,
    rating: 4,
    comment: "The room had good daylight and the kitchen corner was useful for a longer placement. Very practical overall.",
  },
  {
    listingIndex: 12,
    authorIndex: 7,
    rating: 5,
    comment: "Peaceful and comfortable with strong internet. It gave me a reliable base for my semester in Trichy.",
  },
  {
    listingIndex: 13,
    authorIndex: 1,
    rating: 4,
    comment: "The bed nook and desk made excellent use of the space. It was a convenient option close to work and campus.",
  },
  {
    listingIndex: 14,
    authorIndex: 3,
    rating: 4,
    comment: "Good value for the location, with clean shared amenities and a manageable route to the university.",
  },
  {
    listingIndex: 15,
    authorIndex: 9,
    rating: 5,
    comment: "The shared home had a friendly atmosphere and lots of natural light. Flexible terms made planning easy.",
  },
  {
    listingIndex: 16,
    authorIndex: 4,
    rating: 5,
    comment: "The finish is polished without feeling impractical. It was a comfortable and quiet base for my internship.",
  },
  {
    listingIndex: 17,
    authorIndex: 1,
    rating: 4,
    comment: "Lovely garden access and a calm room with enough space to work. The host was quick to answer questions.",
  },
  {
    listingIndex: 18,
    authorIndex: 5,
    rating: 5,
    comment: "Being close to the metro made this room a great choice. It was clean, practical, and ready on arrival.",
  },
  {
    listingIndex: 19,
    authorIndex: 8,
    rating: 4,
    comment: "The study corner was quiet and the room had enough storage for a semester. The location was excellent.",
  },
  {
    listingIndex: 20,
    authorIndex: 0,
    rating: 4,
    comment: "Comfortable shared room with a pleasant view and an easy route to the university. Good value for the area.",
  },
  {
    listingIndex: 21,
    authorIndex: 6,
    rating: 5,
    comment: "The work area and transport links made this ideal for my placement. The studio was clean and thoughtfully arranged.",
  },
  {
    listingIndex: 22,
    authorIndex: 2,
    rating: 4,
    comment: "Excellent neighborhood for a semester in Delhi. Cafes and transit were close, and the room felt secure.",
  },
  {
    listingIndex: 23,
    authorIndex: 4,
    rating: 5,
    comment: "A comfortable room with a short commute and dependable Wi-Fi. The host gave clear instructions before arrival.",
  },
  {
    listingIndex: 24,
    authorIndex: 9,
    rating: 4,
    comment: "Very convenient for office commutes and the room was exactly as pictured. Shared areas were well maintained.",
  },
  {
    listingIndex: 25,
    authorIndex: 1,
    rating: 5,
    comment: "The proper desk made workdays much easier, and transport around Chennai was simple from this location.",
  },
  {
    listingIndex: 26,
    authorIndex: 6,
    rating: 4,
    comment: "A straightforward, well-connected room with everything needed for a semester. The shared facilities were useful.",
  },
];

module.exports = { data: sampleListings, hosts: sampleHosts, reviews: sampleReviews };